config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :admins
  resources :users
  resources :messages
  resources :sessions, :only => [:new, :create, :destroy]
  resources :videos, :only => [:index, :create]

  
  root 'home#index'

  get 'home/signIn',  :to => 'sessions#new', :path => "SignIn"
  get 'home/signOut', :to => 'sessions#destroy', :path => "SignOut"

  get 'users/new', :to => 'users#new', :path => "CreateYourAccount"

  get 'users/destroy', :to => 'users#destroy', :path => "EraseMyAccount"

  get 'users/:id', :to => 'users#show'
  get 'users/edit', :to => 'users#edit', :path => "Edit My Profil"
  get 'users/show', :to => 'users#show', :path => "Show My Profil"
  get 'users/index', :path => "Index"

  get 'home/contact', :to => "messages#new", :path => "ContactUs"

  get 'videos/index', :to => "videos#index", :path => "Media"
  get 'videos/create', :to => "videos#create"
  get 'videos/new', :to => "videos#new", :path => "UploadYourVideo"

end

app/models/message.rb
class Message
  include Mongoid::Document
  field :email, type: String
  field :topic, type: String
  field :msg, type: String
  
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates(:msg, :topic, :email, presence: true)
  validates(:email, format: { :with => EMAIL_REGEX })
  validates(:msg, length: { :maximum => 1024 } )
end

app/models/user.rb
class User
  include Mongoid::Document
	
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  field :login, type: String, :default => ""
  field :email, type: String, :default => ""
  field :password, type: String, :default => ""
  #field :password_confirmation, type: String, :default => ""
  field :encrypted_password, type: String
  field :salt, type: String

  validates(:login, :email, uniqueness: true)
  validates(:email, format: { :with => EMAIL_REGEX })
  validates(:login, length: { :maximum => 64, :minimum => 6 } )
  validates(:encrypted_password, length: { :minimum => 6 }, :confirmation => true, :if => :password )

  before_save :encrypt_password
  
  def has_password?(password_soumis)
	encrypted_password == encrypt(password_soumis)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.find_by_id(id)
    find(id) rescue nil
  end
  def self.find_by_email(email)
  	find(email) rescue nil
  end
  private
    
    def self.authenticate_with_salt(id, cookie_salt)
    	user = find_by_id(id)
    	(user && user.salt == cookie_salt) ? user : nil
    end

    def encrypt_password
      self.encrypted_password = encrypt(encrypted_password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{encrypted_password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/models/video.rb
class Video
  include Mongoid::Document
  include Mongoid::Timestamps

  field :link, type: String, :default => ""
  field :email, type: String, :default => ""
  field :visible, type: Boolean, :default => false
#  field :created_at, type: DateTime  # Add this line

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates(:link, :email, presence: true)
  validates(:email, format: { :with => EMAIL_REGEX })
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@videoAll = Video.order_by(:created_at => "desc")
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	def new
		@message = Message.new
	end
	def create
		@message = Message.new(message_params)
		if @message.save
			flash[:success] = "Your Message Is Send"
      		redirect_to root_path
		else
		end
	end
	
	def message_params
		params.require(:message).permit(:email, :topic, :msg)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		@titre = "S'identifier"
	end
	def create
    	user = User.authenticate(params[:session][:email],
                             params[:session][:password])
		if user.nil?
		  	flash.now[:error] = "Combinaison mail/mot de passe invalide."
			render 'new'
		else
	      sign_in user
	      redirect_to user
		end
	end

	def destroy
    	sign_out
    	redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :correct_user, :only => [:edit, :update, :destroy]
	before_filter :authenticate, :only => [:edit, :update]
	
	def destroy
		sign_out
		User.find(params[:id]).destroy
		flash[:success] = "Utilisateur supprimé."
		redirect_to root_path
	end
	
	def new
		@user = User.new
	end
	
	def show
		@user = User.find(params[:id])
		@titre = @user.login
	end
	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			flash[:success] = "Profil actualisé."
			redirect_to @user
		else
			@titre = "Édition profil"
			render 'edit'
		end
	end
	def create
		@user = User.new(user_params)
		#raise @user.to_a.to_s
		if @user.save
			sign_in @user
			flash[:success] = "Welcome on BlackHole"
      		redirect_to root_path
		else
			render 'new'
		end
	end
	def user_params
		params.require(:user).permit(:login, :email, :encrypted_password, :salt)
	end
	def edit
    	@user = User.find(params[:id])
    	@titre = "Édit Profil"
    end
    def current_user?(user)
    	user == current_user
  	end
    def correct_user
    	@user = User.find(params[:id])
    	redirect_to(root_path) unless current_user?(@user)
    end

    def index
        @titre = "All Users"
	    @users = User.all
    end

      private

    def authenticate
      deny_access unless signed_in?
    end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	def new
		@videoUp = Video.new
	end
	def create
		@videoUp = Video.new(videos_params)
		tmp_str = @videoUp.link.split('/')
		@videoUp.link = tmp_str[3].to_s
		if @videoUp.save
			flash[:success] = "Your Video Is Up"
		else
			flash[:error] = "Your Video Isn't Up"
		end
	end

	def index
		@videoAll = Video.order_by(:created_at => "desc")
	end
	
	def videos_params
		params.require(:video).permit(:link, :email)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user=(user)
      @current_user = user
  end

  def current_user
      @current_user ||= user_from_remember_token
  end
    
  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end
  
  private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end

    def signed_in?
    	!current_user.nil?
	  end

	def sign_out
    	cookies.delete(:remember_token)
    	self.current_user = nil
  end

  def deny_access
    store_location
    redirect_to signin_path, :notice => "Please sign in to access this page."
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end

  private

      def store_location
      session[:return_to] = request.fullpath
    end

    def clear_return_to
      session[:return_to] = nil
    end
end

app/helpers/video_helper.rb
module VideoHelper
end

app/views/home/conditions.html.erb
<div class="conditions">
	conditions
</div>

app/views/home/help.html.erb
<div class="help">
</div>

app/views/home/index.html.erb
    <div id="MyAbout" class="container-fluid">
        <section id="about" class="content-section text-center">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>BlackHole</h2>
                <h4>Black Hole est un moba à la troisième personne. Le joueur contrôle un extraterrestre et rejoint une bataille contre neuf autres joueur en mode arena. Chaque joueur sera armé de trois sorts et un ultime.</h4>
            </div>
    </div>
    <div id="MyVideo" class="container-fluid">
        <section id="video" class="content-section text-center">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>Video // <%= link_to "Add Video", videos_new_path %></h2>
                <% if @videoAll != nil%>
                    <% @videoAll.each do |v| %>
                        <% if v.visible %>
                            <iframe width="290" height="180" src="//www.youtube.com/embed/<%= v.link %>" frameborder="0" allowfullscreen></iframe>  
                        <% end %>
                    <% end %>
                <%end%>
            </div>
    </div>
	<!--        <a href="#download" class="btn btn-circle page-scroll">
	<i class="fa fa-angle-double-down animated"></i>
    </a>-->
    </section>
    <!-- Download Section -->
    <div id="MyDownload">
        <section id="download" class="container-fluid content-section text-center">
    	    <div class="col-lg-8 col-lg-offset-2">
    	        <h2>Download BlackHole</h2>
    	        <p>You can download BlackHole for free.</p>
    	        <a href="#" class="btn btn-large btn-primary"><i class="fa fa-download fa-fw"></i>Visit Download Page</a>
    	    </div>
    <!--        <a href="#contact" class="btn btn-circle page-scroll">
                <i class="fa fa-angle-double-down animated"></i>
            </a>-->
        </section>
    </div>
    <!-- Contact Section -->
    <div id="MyContact">
        <section id="contact" class="container-fluid content-section text-center">
                <div class="col-lg-8 col-lg-offset-2">
                    <h2>Contact Staff</h2>
                    <ul class="list-inline banner-social-buttons">
                        <li>
                            <a href="#" class="btn btn-large btn-primary"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                        </li>
                        <li>
                            <a href="/messages/new" class="btn btn-large btn-primary"><i class="fa fa-envelope fa-fw"></i> <span class="network-name">Mail</span></a>
                        </li>
                    </ul>
                </div>
        </section>
    </div>

<script type="text/javascript">
$(document).ready(function(){
    $('a[href^="#"]').on('click',function (e) {
        e.preventDefault();

        var target = this.hash;
        $target = $(target);

        $('html, body').stop().animate({
            'scrollTop': $target.offset().top
        }, 2000, 'swing', function () {
            window.location.hash = target;
        });
    });
    $('#MyAbout').css("heigth", $(window).height());
    $('#MyVideo').css("heigth", $(window).height());
    $('#MyContact').css("heigth", $(window).height());
    $('#MyDownload').css("heigth", $(window).height());
});
</script>

app/views/home/legals.html.erb
<div class="legals">
	legals
</div>

app/views/home/team.html.erb
<div class="theTeam">
	the team
</div>

app/views/layouts/_footer.html.erb
<footer>
</footer>

app/views/layouts/_header.html.erb
    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="/">BlackHole</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                <li><%= link_to "About", "#about" %></li>
                <li><%= link_to "Media", "#video" %></li>
                <li><%= link_to "Download", "#download" %></li>
                <li><%= link_to "Contact", "#contact" %></li>
                <% if signed_in? %>
                <li><%= link_to "Profil", edit_user_path(current_user) %></li>
                <li><%= link_to "Déconnexion", '/SignOut', :method => :delete %></li>
                <% else %>
                <li><%= link_to "S'identifier", '/SignIn' %></li>
                <li><%= link_to "S'inscrire !", users_new_path %></li>
                <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery/jquery-1.8.0.js"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.22/jquery-ui.js"></script>
    

    <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">



    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">

	<title>BlackHole</title>
        <%= stylesheet_link_tag "application", media: "all"%>
        <%= stylesheet_link_tag "/stylesheets/", :rel => "stylesheet/less" %>
  		<%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
 
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
<div div="header">
    <%= render 'layouts/header' %>
</div>
<div class="container-fluid" style="margin-top:250px;">
    <%= yield %>
</div>
<div div="footer">
    <%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/messages/new.html.erb
<div class="container">

  <h1>Contact Us</h1>
  <%= form_for @message, html: { class: "form-horizontal", role: "form" } do |f| %>
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
      <div class="col-sm-10">
        <%= email_field("message", "email", :placeholder => "Enter Your Email", class:"form-control", id:"inputEmail3") %>
      </div>
    </div>
    <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">Object</label>
        <div class="col-sm-10">
          <%= text_field("message", "topic", :placeholder => "Enter Your Object", class:"form-control", id:"inputEmail3") %>
        </div>
    </div>
    <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">Message</label>
        <div class="col-sm-10">
          <%= text_area("message", "msg", :placeholder => "Enter Your Message", class:"form-control", id:"inputEmail3") %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= submit_tag("Send Message", class:"btn btn-large btn-primary") %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if @current_user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@current_user.errors.count, "erreur") %> 
        ont empêché d'enregistrer votre inscription</h2>
    <p>Merci de corriger ces champs :</p>
    <ul>
    <% @current_user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
  <div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Edit Your Account</h1>
      <%= form_for @user, html: { class: "form-horizontal", role: "form" } do |f| %>
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">Password</label>
            <div class="col-sm-10">
              <%= f.password_field("encrypted_password", :placeholder => "Enter Your New Password", class:"form-control", id:"inputEmail3") %>
          </div>
        </div>
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">Password Confirmation</label>
            <div class="col-sm-10">
              <%= f.password_field("password_confirmation", :placeholder => "Confirm Your New Password", class:"form-control", id:"inputEmail3") %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= submit_tag("Update Your Account", class:"btn btn-large btn-primary") %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/users/index.html.erb
<h1>Tous les utilisateurs</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.login, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<div class="container">
<% provide(:title, 'Sign up') %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Create Your Account</h1>
      <%= form_for @user, html: { class: "form-horizontal", role: "form" } do |f| %>
        <div class="form-group">
          <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
          <div class="col-sm-10">
            <%= f.email_field("email", :placeholder => "Enter Your Email", class:"form-control", id:"inputEmail3") %>
          </div>
        </div>
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">Login</label>
            <div class="col-sm-10">
              <%= f.text_field("login", :placeholder => "Enter Your Login", class:"form-control", id:"inputEmail3") %>
          </div>
        </div>
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">Password</label>
            <div class="col-sm-10">
              <%= f.password_field("encrypted_password", :placeholder => "Enter Your Password", class:"form-control", id:"inputEmail3") %>
          </div>
        </div>
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">Password Confirmation</label>
            <div class="col-sm-10">
              <%= f.password_field("password_confirmation", :placeholder => "Confirm Your Password", class:"form-control", id:"inputEmail3") %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= submit_tag("Create Your Account", class:"btn btn-large btn-primary") %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<table class="profile" summary="Information profil">
  <tr>
    <td class="main">
      <h1>
        <%= @user.login %>
      </h1>
    </td>
    <td class="sidebar round">
      <strong>Login</strong> <%= @user.login %><br />
      <strong>URL</strong>  <%= link_to user_path(@user), @user %>
    </td>
  </tr>
</table>

app/views/videos/index.html.erb
<%= link_to "Add Video", videos_new_path %>

<% if @videoAll != nil%>
	<% @videoAll.each do |v| %>
		<% if v.visible %>
			<iframe width="560" height="315" src="//www.youtube.com/embed/<%= v.link %>" frameborder="0" allowfullscreen></iframe>	
		<% end %>
	<% end %>
<%end%>

app/views/videos/new.html.erb
<h1>Upload Your Video</h1>
  <%= form_for @videoUp, html: { class: "form-horizontal", role: "form" } do |f| %>
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
      <div class="col-sm-10">
        <%= f.text_field :email, title: "Video Link", placeholder: "Your Email" , class:"form-control"%>
      </div>
    </div>
    <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">Object</label>
        <div class="col-sm-10">
          <%= f.text_field :link, title: "Description", placeholder: "Video Link",class:"form-control" %>
        </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "Submit Link", class:"btn btn-large btn-primary" %>
      </div>
    </div>
  <% end %>
</div>